=== asc1535/Datenbanken/Lab/Lab1/BarWorklog/management.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT management (employee*, country*, profession*)>

<!ELEMENT country EMPTY>
<!ATTLIST country	country_id		ID		#REQUIRED
					country_name	CDATA	#REQUIRED
					nationality		CDATA	#REQUIRED>

<!ELEMENT employee (address*, phone*, email*, employment*)>
<!ATTLIST employee	employee_id	ID	#REQUIRED
					SVN			CDATA	#REQUIRED
					fname		CDATA	#REQUIRED
					lname		CDATA	#REQUIRED
					birthdate	CDATA	#REQUIRED
					comment		CDATA	#IMPLIED
					country_id	IDREF	#REQUIRED>

<!ELEMENT address EMPTY>
<!ATTLIST address	street_name		CDATA	#REQUIRED
					city_name		CDATA	#REQUIRED
					zip_code		CDATA	#REQUIRED
					country_id		IDREF	#REQUIRED>

<!ELEMENT phone EMPTY>
<!ATTLIST phone	phone_no	CDATA	#REQUIRED>

<!ELEMENT email EMPTY>
<!ATTLIST email	email_addr	CDATA	#REQUIRED>

<!ELEMENT employment (time_record*)>
<!ATTLIST employment	employment_id	ID		#REQUIRED
						prof_id			IDREF	#REQUIRED
						start_date		CDATA	#REQUIRED
						end_date		CDATA	#IMPLIED
						hours			CDATA	#REQUIRED
						vacation_hours	CDATA	#REQUIRED
						iban			CDATA	#REQUIRED
						bic				CDATA	#REQUIRED>

<!ELEMENT time_record EMPTY>
<!ATTLIST time_record	time_record_id	ID		#REQUIRED
						f_timestamp		CDATA	#REQUIRED
						l_timestamp		CDATA	#REQUIRED
						comment			CDATA	#IMPLIED>

<!ELEMENT profession EMPTY>
<!ATTLIST profession	prof_id		ID		#REQUIRED
						profession	(KellnerIn|BarkeeperIn|Reinigungsfachkraft|Koch|TÃ¤nzerin|Hausmeister)	#REQUIRED>

=== asc1535/Datenbanken/Lab/Lab2/BarWorklog/management.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE management SYSTEM "management.dtd">
<management>
<!-- Test -->
	<employee employee_id="employee_00001" SVN="2410240196" fname="Simon" lname="Mair" birthdate="1996-01-24" country_id="AUT" comment="testcomment">
		<address street_name="Tannenfeldstraße 40" city_name="Meiningen" zip_code="6812" country_id="AUT"/>
		<phone phone_no="0664 3803383"/>
		<email email_addr="simon.mair@students.fhv.at"/>
		<employment employment_id="employment_0000000001" prof_id="profession_00001" start_date="2017-12-20" end_date="2017-12-21" hours="8.00" vacation_hours="3.00" iban="AT46238412452584" bic="RVVGAT2B427">
			<time_record time_record_id="time_record_0000000001" f_timestamp="2017-12-20T08:00:00" l_timestamp="2017-12-20T16:00:00" comment="Bla Bla Bla"/>
		</employment>
		<employment employment_id="employment_0000000022" prof_id="profession_00002" start_date="2017-12-20" end_date="2017-12-21" hours="8.00" vacation_hours="3.00" iban="AT46238412452584" bic="RVVGAT2B427">
			<time_record time_record_id="time_record_0000000081" f_timestamp="2017-12-20T08:00:00" l_timestamp="2017-12-20T16:00:00" comment="Bla Bla Bla"/>
		</employment>
	</employee>
	
	<employee lname="Musterman" birthdate="1990-04-05" SVN="2410240192" employee_id="employee_00002" country_id="GER" fname="Esel">
		<address zip_code="2442" city_name="Wademünde" street_name="Flussstraße 3" country_id="GER"/>
		<address zip_code="2233" city_name="BERN" street_name="DIE KURVE 3" country_id="CHE"/>
		<phone phone_no="0399 2253332"/>
		<phone phone_no="3321 4555233"/>
		<email email_addr="musterm@monney.com"/>
		<email email_addr="jonniBgood@oww.com"/>
		<employment hours="56" start_date="2017-12-20" employment_id="employment_0000000002" iban="AT46238412452584" bic="RVVGAT2B427" prof_id="profession_00001" vacation_hours="40">
			<time_record time_record_id="time_record_0000000002" l_timestamp="2017-12-20T08:00:00" f_timestamp="2017-12-20T16:00:00"/>
			<time_record time_record_id="time_record_0000000003" l_timestamp="2017-12-21T08:00:00" f_timestamp="2017-12-21T16:00:00"/>
			<time_record time_record_id="time_record_0000000004" l_timestamp="2017-12-22T08:00:00" f_timestamp="2017-12-22T16:00:00"/>
			<time_record time_record_id="time_record_0000000005" l_timestamp="2017-12-23T08:00:00" f_timestamp="2017-12-23T16:00:00"/>
			<time_record time_record_id="time_record_0000000006" l_timestamp="2017-12-24T08:00:00" f_timestamp="2017-12-24T16:00:00"/>
			<time_record time_record_id="time_record_0000000007" l_timestamp="2017-12-25T08:00:00" f_timestamp="2017-12-25T16:00:00"/>
			<time_record time_record_id="time_record_0000000008" l_timestamp="2017-12-26T08:00:00" f_timestamp="2017-12-26T16:00:00"/>
		</employment>
	</employee>
	
	<employee lname="Serge" birthdate="1993-02-05" SVN="2410240192" employee_id="employee_00003" country_id="AZE" fname="Muruk">
		<address zip_code="2542" city_name="Bulm" street_name="Southstreet 3" country_id="AZE"/>
		<address zip_code="1111" city_name="BERN" street_name="DIE KURVE 7" country_id="CHE"/>
		<phone phone_no="0339 2552332"/>
		<phone phone_no="3391 4555999"/>
		<email email_addr="musborm@mouuey.com"/>
		<email email_addr="Rideer@w.com"/>
		<employment hours="56" start_date="2017-12-20" employment_id="employment_0000000003" iban="AT46238412452584" bic="RVVGAT2B427" prof_id="profession_00002" vacation_hours="40">
			<time_record time_record_id="time_record_0000000009" l_timestamp="2017-12-20T08:00:00" f_timestamp="2017-12-20T16:00:00"/>
			<time_record time_record_id="time_record_0000000010" l_timestamp="2017-12-21T08:00:00" f_timestamp="2017-12-21T16:00:00"/>
			<time_record time_record_id="time_record_0000000011" l_timestamp="2017-12-22T08:00:00" f_timestamp="2017-12-22T16:00:00"/>
			<time_record time_record_id="time_record_0000000012" l_timestamp="2017-12-23T08:00:00" f_timestamp="2017-12-23T16:00:00"/>
			<time_record time_record_id="time_record_0000000013" l_timestamp="2017-12-24T08:00:00" f_timestamp="2017-12-24T16:00:00"/>
			<time_record time_record_id="time_record_0000000014" l_timestamp="2017-12-25T08:00:00" f_timestamp="2017-12-25T16:00:00"/>
			<time_record time_record_id="time_record_0000000015" l_timestamp="2017-12-26T08:00:00" f_timestamp="2017-12-26T16:00:00"/>
		</employment>
	</employee>
	
	<employee fname="Slim" lname="Shady" birthdate="1972-01-01" SVN="27202492192" employee_id="employee_00004" country_id="USA" >
		<address zip_code="0815" city_name="Detroit" street_name="Trailerpark" country_id="USA"/>
		<phone phone_no="01 0003 0004"/>
		<email email_addr="slim.shady@shady-records.com"/>
		<employment hours="2" start_date="1972-01-01" employment_id="employment_0000000004" iban="US37891241423" bic="GENODES1TET" prof_id="profession_00006" vacation_hours="200">
			<time_record time_record_id="time_record_0000000016" l_timestamp="2017-12-20T08:00:00" f_timestamp="2017-12-20T16:00:00"/>
			<time_record time_record_id="time_record_0000000017" l_timestamp="2017-12-21T08:00:00" f_timestamp="2017-12-21T16:00:00"/>
			<time_record time_record_id="time_record_0000000018" l_timestamp="2017-12-22T08:00:00" f_timestamp="2017-12-22T16:00:00"/>
			<time_record time_record_id="time_record_0000000019" l_timestamp="2017-12-23T08:00:00" f_timestamp="2017-12-23T16:00:00"/>
			<time_record time_record_id="time_record_0000000020" l_timestamp="2017-12-24T08:00:00" f_timestamp="2017-12-24T16:00:00"/>
			<time_record time_record_id="time_record_0000000021" l_timestamp="2017-12-25T08:00:00" f_timestamp="2017-12-25T16:00:00"/>
			<time_record time_record_id="time_record_0000000022" l_timestamp="2017-12-26T08:00:00" f_timestamp="2017-12-26T16:00:00"/>
		</employment>
	</employee>
	
	<employee fname="Snoop" lname="Dogg" birthdate="1971-01-01" SVN="2721340196" employee_id="employee_00005" country_id="USA" >
		<address zip_code="0815" city_name="Los Angeles" street_name="Long Beach" country_id="USA"/>
		<phone phone_no="119 101 101 100"/>
		<email email_addr="snoop@master-kush.com"/>
		<employment hours="7" start_date="1971-01-01" employment_id="employment_0000000005" iban="US37891241421" bic="GENODES1TET" prof_id="profession_00002" vacation_hours="100">
			<time_record time_record_id="time_record_0000000023" l_timestamp="2017-12-20T08:00:00" f_timestamp="2017-12-20T16:00:00"/>
			<time_record time_record_id="time_record_0000000024" l_timestamp="2017-12-21T08:00:00" f_timestamp="2017-12-21T16:00:00"/>
			<time_record time_record_id="time_record_0000000025" l_timestamp="2017-12-22T08:00:00" f_timestamp="2017-12-22T16:00:00"/>
			<time_record time_record_id="time_record_0000000026" l_timestamp="2017-12-23T08:00:00" f_timestamp="2017-12-23T16:00:00"/>
			<time_record time_record_id="time_record_0000000027" l_timestamp="2017-12-24T08:00:00" f_timestamp="2017-12-24T16:00:00"/>
			<time_record time_record_id="time_record_0000000028" l_timestamp="2017-12-25T08:00:00" f_timestamp="2017-12-25T16:00:00"/>
			<time_record time_record_id="time_record_0000000029" l_timestamp="2017-12-26T08:00:00" f_timestamp="2017-12-26T16:00:00"/>
		</employment>
	</employee>
	
	<employee fname="Will" lname="Smith" birthdate="1980-01-01" SVN="2721742198" employee_id="employee_00006" country_id="USA" >
		<address zip_code="0815" city_name="Washington DC" street_name="Levis St NE" country_id="USA"/>
		<phone phone_no="09 999 888 777"/>
		<email email_addr="willy.from@west-philly.com"/>
		<employment hours="20" start_date="1980-01-01" employment_id="employment_0000000006" iban="US37891249421" bic="GENODES1TET" prof_id="profession_00005" vacation_hours="50">
			<time_record time_record_id="time_record_0000000030" l_timestamp="2017-12-20T08:00:00" f_timestamp="2017-12-20T16:00:00"/>
			<time_record time_record_id="time_record_0000000031" l_timestamp="2017-12-21T08:00:00" f_timestamp="2017-12-21T16:00:00"/>
			<time_record time_record_id="time_record_0000000032" l_timestamp="2017-12-22T08:00:00" f_timestamp="2017-12-22T16:00:00"/>
			<time_record time_record_id="time_record_0000000033" l_timestamp="2017-12-23T08:00:00" f_timestamp="2017-12-23T16:00:00"/>
			<time_record time_record_id="time_record_0000000034" l_timestamp="2017-12-24T08:00:00" f_timestamp="2017-12-24T16:00:00"/>
			<time_record time_record_id="time_record_0000000035" l_timestamp="2017-12-25T08:00:00" f_timestamp="2017-12-25T16:00:00"/>
			<time_record time_record_id="time_record_0000000036" l_timestamp="2017-12-26T08:00:00" f_timestamp="2017-12-26T16:00:00"/>
		</employment>
	</employee>
	
	<employee fname="Method" lname="Man" birthdate="19750-01-01" SVN="1721742198" employee_id="employee_00007" country_id="USA" >
		<address zip_code="0815" city_name="New York City" street_name="Atlantic Ave" country_id="USA"/>
		<phone phone_no="09 999 888 111"/>
		<email email_addr="method.man@wu-tang-clan.gov"/>
	</employee>
	
	<employee employee_id="employee_00008" SVN="2410240192" fname="Alexander" lname="Zeyer" birthdate="1993-04-27" country_id="GER">
		<address street_name="Kehlerau 1a" city_name="Dornbirn" zip_code="6850" country_id="AUT"/>
		<phone phone_no="0664 889900"/>
		<email email_addr="alexander.zeyer@students.fhv.at"/>
		<employment employment_id="employment_0000000008" prof_id="profession_00005" start_date="2017-12-20" end_date="2017-12-21" hours="8.00" vacation_hours="3.00" iban="AT46238412452584" bic="RVVGAT2B427">
			<time_record time_record_id="time_record_0000000037" f_timestamp="2017-12-20T08:00:00" l_timestamp="2017-12-20T16:00:00"/>
		</employment>
	</employee>
	
	<employee lname="Norris" birthdate="1990-04-05" SVN="2410240192" employee_id="employee_00009" country_id="GER" fname="Chuck">
		<address zip_code="2442" city_name="Wademünde" street_name="Flussstraße 3" country_id="GER"/>
		<address zip_code="2233" city_name="BERN" street_name="DIE GERADE 3" country_id="CHE"/>
		<phone phone_no="0399 2253332"/>
		<phone phone_no="3321 4555233"/>
